compressionLevel: 0

defaultSemverRangePrefix: ""

enableTelemetry: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0066
    level: error

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/git-hooks.cjs
    spec: git-hooks

yarnPath: .yarn/releases/yarn-4.5.1.cjs
