compressionLevel: 0

defaultSemverRangePrefix: ""

enableTelemetry: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0066
    level: error

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/git-hooks.cjs
    spec: git-hooks
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
