compressionLevel: 0

defaultSemverRangePrefix: ""

enableTelemetry: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0066
    level: error

nmMode: hardlinks-local

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
