import { snapshot, type TestContext, test } from "node:test";
import { ScriptStore } from "./ScriptStore.js";

snapshot.setResolveSnapshotPath((filename) =>
	filename !== undefined
		? `${filename.replace("/output/", "/source/")}.snapshot`
		: "",
);

test("reliably detects existence", async (t: TestContext) => {
	t.assert.strictEqual(await ScriptStore.exists("test/fixtures/default"), true);
	t.assert.strictEqual(await ScriptStore.exists("invalid"), false);
});

test("should load an existing store", async (t: TestContext) => {
	const store = new ScriptStore("test/fixtures/default");
	await store.load();

	t.assert.strictEqual(
		store.comment,
		"This file is generated by node-scripts-docs.",
	);
	t.assert.snapshot(store.globalScripts);
	t.assert.snapshot(store.scripts);
	t.assert.strictEqual(store.version, 1);
});

test("parses locator as expected", (t: TestContext) => {
	const parsed = ScriptStore.parseScriptLocator(
		"test:coverage→node-scripts-docs",
	);
	t.assert.strictEqual(parsed.projectName, "node-scripts-docs");
	t.assert.strictEqual(parsed.scriptName, "test:coverage");
});

test("renders locator as expected", (t: TestContext) => {
	const rendered = ScriptStore.makeScriptLocator(
		"node-scripts-docs",
		"test:coverage",
	);
	t.assert.strictEqual(rendered, "test:coverage→node-scripts-docs");
});
