name: Documentation Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
        with:
          python-version: 3.x
      - name: Install mkdocs-material
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
      - name: Build/deploy documentation
        run: mkdocs gh-deploy --force
