name: Documentation Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: 3.x

      - name: Install mkdocs-material
        run: pip install mkdocs-material

      - name: Build/deploy documentation
        run: mkdocs gh-deploy --force
