name: Deploy Documentation

on:
  workflow_call:

concurrency:
  group: docs-deploy
  cancel-in-progress: true

jobs:
  docs-deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Select Python version
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        env:
          # renovate: datasource=docker depName=python versioning=semver
          PYTHON_VERSION: "3.12.3"
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install mkdocs-material
        run: pip install mkdocs-material

      - name: Build/deploy documentation
        run: mkdocs gh-deploy --force
