name: Node.JS Tests

on:
  push:
    branches:
      - "main"

jobs:
  qa-main:
    name: Run QA
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 21
        os-release:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os-release }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  qa-successful-main:
    runs-on: ubuntu-22.04
    needs:
      - qa-main
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
